name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Build and push backend image
        run: |
          docker build -t ${{vars.BACKEND_REG_REPO}} ./backend
          docker push ${{vars.BACKEND_REG_REPO}}

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy backend \
            --image ${{vars.BACKEND_REG_REPO}} \
            --platform managed \
            --region ${{vars.REGION}} \
            --${{secrets.ACCESS}}

      - name: Build and push frontend image
        run: |
          docker build -t ${{vars.FRONTEND_REG_REPO}} ./frontend --build-arg NEXT_PUBLIC_API_URL=http://localhost
          docker push ${{vars.FRONTEND_REG_REPO}}

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image ${{vars.FRONTEND_REG_REPO}} \
            --platform managed \
            --region ${{vars.REGION}} \
            --allow-unauthenticated
