name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{vars.REGION}}-docker.pkg.dev

      - name: Build and push backend image
        run: |
          docker build -t ${{vars.BACKEND_REG_REPO}}/app ./backend
          docker push ${{vars.BACKEND_REG_REPO}}/app

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy backend \
            --image ${{vars.BACKEND_REG_REPO}}/app \
            --platform managed \
            --region ${{vars.REGION}} \
            --${{secrets.ACCESS}} \
            --set-env-vars FRONTEND_URL=${{vars.FRONTEND_URL}}

      - name: Build and push frontend image
        run: |
          docker build -t ${{vars.FRONTEND_REG_REPO}}/app ./frontend --build-arg NEXT_PUBLIC_API_URL=${{vars.NEXT_PUBLIC_API_URL}}
          docker push ${{vars.FRONTEND_REG_REPO}}/app

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image ${{vars.FRONTEND_REG_REPO}}/app \
            --platform managed \
            --region ${{vars.REGION}} \
            --${{secrets.ACCESS}}
